[programs.devnet]
myepicproject = "9WK5M7b5YQZKX4KBkSnzHY3Cgxr7C4VReXg9z4U5YVo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/jkmurillo/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
